<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('categories')->delete();

        \DB::table('categories')->insert(array (
            0 =>
            array (
                'id' => 26,
                'name' => 'Промышленные прямоугольные разъемы',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'promyslennye-priamougolnye-razieemy',
                'published' => 1,
                '_lft' => 1,
                '_rgt' => 216,
                'parent_id' => NULL,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            1 =>
            array (
                'id' => 27,
                'name' => 'Контактные вставки',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'kontaktnye-vstavki',
                'published' => 1,
                '_lft' => 2,
                '_rgt' => 23,
                'parent_id' => 26,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            2 =>
            array (
                'id' => 28,
                'name' => 'Корпусы',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'korpusy',
                'published' => 1,
                '_lft' => 24,
                '_rgt' => 47,
                'parent_id' => 26,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            3 =>
            array (
                'id' => 29,
                'name' => 'Обжимные контакты',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'obzimnye-kontakty',
                'published' => 1,
                '_lft' => 48,
                '_rgt' => 63,
                'parent_id' => 26,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            4 =>
            array (
                'id' => 30,
                'name' => 'Аксессуары',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'aksessuary',
                'published' => 1,
                '_lft' => 64,
                '_rgt' => 75,
                'parent_id' => 26,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            5 =>
            array (
                'id' => 31,
                'name' => 'Сальники',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'salniki',
                'published' => 1,
                '_lft' => 76,
                '_rgt' => 107,
                'parent_id' => 26,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            6 =>
            array (
                'id' => 33,
                'name' => 'Серия HA',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-ha',
                'published' => 1,
                '_lft' => 3,
                '_rgt' => 4,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            7 =>
            array (
                'id' => 34,
                'name' => 'Серия HE',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-he',
                'published' => 1,
                '_lft' => 5,
                '_rgt' => 6,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            8 =>
            array (
                'id' => 35,
                'name' => 'Серия HEE',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-hee',
                'published' => 1,
                '_lft' => 7,
                '_rgt' => 8,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            9 =>
            array (
                'id' => 36,
                'name' => 'Серия HD',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-hd',
                'published' => 1,
                '_lft' => 9,
                '_rgt' => 10,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            10 =>
            array (
                'id' => 37,
                'name' => 'Серия HDD',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-hdd',
                'published' => 1,
                '_lft' => 11,
                '_rgt' => 12,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            11 =>
            array (
                'id' => 38,
                'name' => 'Серия HSB',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-hsb',
                'published' => 1,
                '_lft' => 13,
                '_rgt' => 14,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            12 =>
            array (
                'id' => 39,
                'name' => 'Серия HK',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-hk',
                'published' => 1,
                '_lft' => 15,
                '_rgt' => 16,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            13 =>
            array (
                'id' => 40,
                'name' => 'Серия HEAV',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-heav',
                'published' => 1,
                '_lft' => 17,
                '_rgt' => 18,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            14 =>
            array (
                'id' => 41,
                'name' => 'Серия HM',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-hm',
                'published' => 1,
                '_lft' => 19,
                '_rgt' => 20,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            15 =>
            array (
                'id' => 42,
                'name' => 'Серия HQ',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'seriia-hq',
                'published' => 1,
                '_lft' => 21,
                '_rgt' => 22,
                'parent_id' => 27,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            16 =>
            array (
                'id' => 43,
                'name' => 'Типоразмер 3A - пластик',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-3a-plastik',
                'published' => 1,
                '_lft' => 25,
                '_rgt' => 26,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            17 =>
            array (
                'id' => 44,
                'name' => 'Типоразмер 3A - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-3a-metall',
                'published' => 1,
                '_lft' => 27,
                '_rgt' => 28,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            18 =>
            array (
                'id' => 45,
                'name' => 'Типоразмер 10A - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-10a-metall',
                'published' => 1,
                '_lft' => 29,
                '_rgt' => 30,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            19 =>
            array (
                'id' => 46,
                'name' => 'Типоразмер 16A - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-16a-metall',
                'published' => 1,
                '_lft' => 31,
                '_rgt' => 32,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            20 =>
            array (
                'id' => 47,
                'name' => 'Типоразмер 32A - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-32a-metall',
                'published' => 1,
                '_lft' => 33,
                '_rgt' => 34,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            21 =>
            array (
                'id' => 48,
                'name' => 'Типоразмер 6B - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-6b-metall',
                'published' => 1,
                '_lft' => 35,
                '_rgt' => 36,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            22 =>
            array (
                'id' => 49,
                'name' => 'Типоразмер 10B - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-10b-metall',
                'published' => 1,
                '_lft' => 37,
                '_rgt' => 38,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            23 =>
            array (
                'id' => 50,
                'name' => 'Типоразмер 16B - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-16b-metall',
                'published' => 1,
                '_lft' => 39,
                '_rgt' => 40,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            24 =>
            array (
                'id' => 51,
                'name' => 'Типоразмер 24B - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-24b-metall',
                'published' => 1,
                '_lft' => 41,
                '_rgt' => 42,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            25 =>
            array (
                'id' => 52,
                'name' => 'Типоразмер 32B - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-32b-metall',
                'published' => 1,
                '_lft' => 43,
                '_rgt' => 44,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            26 =>
            array (
                'id' => 53,
                'name' => 'Типоразмер 48B - металл',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'tiporazmer-48b-metall',
                'published' => 1,
                '_lft' => 45,
                '_rgt' => 46,
                'parent_id' => 28,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            27 =>
            array (
                'id' => 54,
                'name' => 'Обжимные контакты - 5 Ампер',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'obzimnye-kontakty-5-amper',
                'published' => 1,
                '_lft' => 49,
                '_rgt' => 50,
                'parent_id' => 29,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            28 =>
            array (
                'id' => 55,
                'name' => 'Обжимные контакты - 10 Ампер',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'obzimnye-kontakty-10-amper',
                'published' => 1,
                '_lft' => 51,
                '_rgt' => 52,
                'parent_id' => 29,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            29 =>
            array (
                'id' => 56,
                'name' => 'Обжимные контакты - 16 Ампер',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'obzimnye-kontakty-16-amper',
                'published' => 1,
                '_lft' => 53,
                '_rgt' => 54,
                'parent_id' => 29,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            30 =>
            array (
                'id' => 57,
                'name' => 'Обжимные контакты - 40 Ампер',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'obzimnye-kontakty-40-amper',
                'published' => 1,
                '_lft' => 55,
                '_rgt' => 56,
                'parent_id' => 29,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            31 =>
            array (
                'id' => 58,
                'name' => 'Обжимные контакты - 70 Ампер',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'obzimnye-kontakty-70-amper',
                'published' => 1,
                '_lft' => 57,
                '_rgt' => 58,
                'parent_id' => 29,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            32 =>
            array (
                'id' => 59,
                'name' => 'Обжимные контакты - 100 Ампер',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'obzimnye-kontakty-100-amper',
                'published' => 1,
                '_lft' => 59,
                '_rgt' => 60,
                'parent_id' => 29,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            33 =>
            array (
                'id' => 60,
                'name' => 'Обжимные контакты - 200 Ампер',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'obzimnye-kontakty-200-amper',
                'published' => 1,
                '_lft' => 61,
                '_rgt' => 62,
                'parent_id' => 29,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            34 =>
            array (
                'id' => 61,
                'name' => 'Пластиковые сальники',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'plastikovye-salniki',
                'published' => 1,
                '_lft' => 77,
                '_rgt' => 78,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            35 =>
            array (
                'id' => 62,
                'name' => 'Металлические сальники',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'metalliceskie-salniki',
                'published' => 1,
                '_lft' => 79,
                '_rgt' => 80,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            36 =>
            array (
                'id' => 64,
                'name' => 'Металлические контргайки',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'metalliceskie-kontrgaiki',
                'published' => 1,
                '_lft' => 81,
                '_rgt' => 82,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            37 =>
            array (
                'id' => 65,
                'name' => 'Пластиковые переходники',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'plastikovye-perexodniki',
                'published' => 1,
                '_lft' => 83,
                '_rgt' => 84,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            38 =>
            array (
                'id' => 66,
                'name' => 'Металлические переходники',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'metalliceskie-perexodniki',
                'published' => 1,
                '_lft' => 85,
                '_rgt' => 86,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            39 =>
            array (
                'id' => 67,
                'name' => 'Футорки пластиковые',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'futorki-plastikovye',
                'published' => 1,
                '_lft' => 87,
                '_rgt' => 88,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            40 =>
            array (
                'id' => 68,
                'name' => 'Футорки металлические',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'futorki-metalliceskie',
                'published' => 1,
                '_lft' => 89,
                '_rgt' => 90,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            41 =>
            array (
                'id' => 69,
                'name' => 'Пластиковые заглушки круглые',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'plastikovye-zagluski-kruglye',
                'published' => 1,
                '_lft' => 91,
                '_rgt' => 92,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            42 =>
            array (
                'id' => 70,
                'name' => 'Металлические заглушки шестигранные',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'metalliceskie-zagluski-sestigrannye',
                'published' => 1,
                '_lft' => 93,
                '_rgt' => 94,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            43 =>
            array (
                'id' => 71,
            'name' => 'Пластиковые муфты для металлорукавов (быстрого соединения)',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'plastikovye-mufty-dlia-metallorukavov-bystrogo-soedineniia',
                'published' => 1,
                '_lft' => 95,
                '_rgt' => 96,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            44 =>
            array (
                'id' => 72,
                'name' => 'Муфты для металлорукавов металлические прямые',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'mufty-dlia-metallorukavov-metalliceskie-priamye',
                'published' => 1,
                '_lft' => 97,
                '_rgt' => 98,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            45 =>
            array (
                'id' => 73,
                'name' => 'Металлические сальники для многожильного кабеля',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'metalliceskie-salniki-dlia-mnogozilnogo-kabelia',
                'published' => 1,
                '_lft' => 99,
                '_rgt' => 100,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            46 =>
            array (
                'id' => 74,
                'name' => 'Металлические сальники с заземлением EMC',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'metalliceskie-salniki-s-zazemleniem-emc',
                'published' => 1,
                '_lft' => 101,
                '_rgt' => 102,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            47 =>
            array (
                'id' => 75,
            'name' => 'Сальники с внешней разгрузкой от натяжения (с двойной фиксацией)',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'salniki-s-vnesnei-razgruzkoi-ot-natiazeniia-s-dvoinoi-fiksaciei',
                'published' => 1,
                '_lft' => 103,
                '_rgt' => 104,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            48 =>
            array (
                'id' => 79,
            'name' => 'Полукомплекты (кожух + вставка)',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-kozux-vstavka',
                'published' => 1,
                '_lft' => 108,
                '_rgt' => 161,
                'parent_id' => 26,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            49 =>
            array (
                'id' => 89,
                'name' => 'Комплекты промышленных разъемов',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-promyslennyx-razieemov',
                'published' => 1,
                '_lft' => 162,
                '_rgt' => 213,
                'parent_id' => 26,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            50 =>
            array (
                'id' => 90,
                'name' => 'Комплекты контактных вставок',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-kontaktnyx-vstavok',
                'published' => 1,
                '_lft' => 214,
                '_rgt' => 215,
                'parent_id' => 26,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            51 =>
            array (
                'id' => 91,
                'name' => 'Полукомплекты серии HA',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-serii-ha',
                'published' => 1,
                '_lft' => 109,
                '_rgt' => 122,
                'parent_id' => 79,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            52 =>
            array (
                'id' => 92,
                'name' => 'Полукомплекты на основе контактных вставок HA-003',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-ha-003',
                'published' => 1,
                '_lft' => 110,
                '_rgt' => 111,
                'parent_id' => 91,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            53 =>
            array (
                'id' => 93,
                'name' => 'Полукомплекты на основе контактных вставок HA-004',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-ha-004',
                'published' => 1,
                '_lft' => 112,
                '_rgt' => 113,
                'parent_id' => 91,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            54 =>
            array (
                'id' => 94,
                'name' => 'Полукомплекты на основе контактных вставок HA-010',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-ha-010',
                'published' => 1,
                '_lft' => 114,
                '_rgt' => 115,
                'parent_id' => 91,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            55 =>
            array (
                'id' => 95,
                'name' => 'Полукомплекты на основе контактных вставок HA-016',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-ha-016',
                'published' => 1,
                '_lft' => 116,
                '_rgt' => 117,
                'parent_id' => 91,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            56 =>
            array (
                'id' => 96,
                'name' => 'Полукомплекты на основе контактных вставок HA-032',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-ha-032',
                'published' => 1,
                '_lft' => 118,
                '_rgt' => 119,
                'parent_id' => 91,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            57 =>
            array (
                'id' => 97,
                'name' => 'Полукомплекты серии HE',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-serii-he',
                'published' => 1,
                '_lft' => 123,
                '_rgt' => 136,
                'parent_id' => 79,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            58 =>
            array (
                'id' => 98,
                'name' => 'Полукомплекты на основе контактных вставок HE-006',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-he-006',
                'published' => 1,
                '_lft' => 124,
                '_rgt' => 125,
                'parent_id' => 97,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            59 =>
            array (
                'id' => 99,
                'name' => 'Полукомплекты на основе контактных вставок HE-010',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-he-010',
                'published' => 1,
                '_lft' => 126,
                '_rgt' => 127,
                'parent_id' => 97,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            60 =>
            array (
                'id' => 100,
                'name' => 'Полукомплекты на основе контактных вставок HE-016',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-he-016',
                'published' => 1,
                '_lft' => 128,
                '_rgt' => 129,
                'parent_id' => 97,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            61 =>
            array (
                'id' => 101,
                'name' => 'Полукомплекты на основе контактных вставок HE-024',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-he-024',
                'published' => 1,
                '_lft' => 130,
                '_rgt' => 131,
                'parent_id' => 97,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            62 =>
            array (
                'id' => 102,
                'name' => 'Полукомплекты на основе контактных вставок HE-032',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-he-032',
                'published' => 1,
                '_lft' => 132,
                '_rgt' => 133,
                'parent_id' => 97,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:32',
            ),
            63 =>
            array (
                'id' => 103,
                'name' => 'Полукомплекты на основе контактных вставок HE-048',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-he-048',
                'published' => 1,
                '_lft' => 134,
                '_rgt' => 135,
                'parent_id' => 97,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            64 =>
            array (
                'id' => 130,
                'name' => 'Полукомплекты серии HSB',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-serii-hsb',
                'published' => 1,
                '_lft' => 137,
                '_rgt' => 146,
                'parent_id' => 79,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            65 =>
            array (
                'id' => 131,
                'name' => 'Полукомплекты на основе контактных вставок HSBS-004',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hsbs-004',
                'published' => 1,
                '_lft' => 138,
                '_rgt' => 139,
                'parent_id' => 130,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            66 =>
            array (
                'id' => 132,
                'name' => 'Полукомплекты на основе контактных вставок HSB-004',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hsb-004',
                'published' => 1,
                '_lft' => 140,
                '_rgt' => 141,
                'parent_id' => 130,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            67 =>
            array (
                'id' => 133,
                'name' => 'Полукомплекты на основе контактных вставок HSB-006',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hsb-006',
                'published' => 1,
                '_lft' => 142,
                '_rgt' => 143,
                'parent_id' => 130,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            68 =>
            array (
                'id' => 134,
                'name' => 'Полукомплекты на основе контактных вставок HSB-012',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hsb-012',
                'published' => 1,
                '_lft' => 144,
                '_rgt' => 145,
                'parent_id' => 130,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            69 =>
            array (
                'id' => 135,
                'name' => 'Полукомплекты серии HK',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-serii-hk',
                'published' => 1,
                '_lft' => 147,
                '_rgt' => 160,
                'parent_id' => 79,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            70 =>
            array (
                'id' => 138,
                'name' => 'Полукомплекты на основе контактных вставок HK-004/0',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hk-0040',
                'published' => 1,
                '_lft' => 148,
                '_rgt' => 149,
                'parent_id' => 135,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            71 =>
            array (
                'id' => 139,
                'name' => 'Полукомплекты на основе контактных вставок HK-004/2',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hk-0042',
                'published' => 1,
                '_lft' => 150,
                '_rgt' => 151,
                'parent_id' => 135,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            72 =>
            array (
                'id' => 140,
                'name' => 'Полукомплекты на основе контактных вставок HWK-006/6',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hwk-0066',
                'published' => 1,
                '_lft' => 152,
                '_rgt' => 153,
                'parent_id' => 135,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            73 =>
            array (
                'id' => 144,
                'name' => 'Полукомплекты на основе контактных вставок HK-006/6',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hk-0066',
                'published' => 1,
                '_lft' => 154,
                '_rgt' => 155,
                'parent_id' => 135,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            74 =>
            array (
                'id' => 145,
                'name' => 'Полукомплекты на основе контактных вставок HK-008/0',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hk-0080',
                'published' => 1,
                '_lft' => 156,
                '_rgt' => 157,
                'parent_id' => 135,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            75 =>
            array (
                'id' => 146,
                'name' => 'Полукомплекты на основе контактных вставок HK-004/8',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-na-osnove-kontaktnyx-vstavok-hk-0048',
                'published' => 1,
                '_lft' => 158,
                '_rgt' => 159,
                'parent_id' => 135,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            76 =>
            array (
                'id' => 155,
                'name' => 'Комплекты серии HA',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-serii-ha',
                'published' => 1,
                '_lft' => 163,
                '_rgt' => 174,
                'parent_id' => 89,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            77 =>
            array (
                'id' => 156,
                'name' => 'Комплекты серии HE',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-serii-he',
                'published' => 1,
                '_lft' => 175,
                '_rgt' => 188,
                'parent_id' => 89,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            78 =>
            array (
                'id' => 157,
                'name' => 'Комплекты серии HSB',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-serii-hsb',
                'published' => 1,
                '_lft' => 189,
                '_rgt' => 198,
                'parent_id' => 89,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            79 =>
            array (
                'id' => 158,
                'name' => 'Комплекты серии HK',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-serii-hk',
                'published' => 1,
                '_lft' => 199,
                '_rgt' => 212,
                'parent_id' => 89,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            80 =>
            array (
                'id' => 159,
                'name' => 'Комплекты HA-003',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-ha-003',
                'published' => 1,
                '_lft' => 164,
                '_rgt' => 165,
                'parent_id' => 155,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            81 =>
            array (
                'id' => 160,
                'name' => 'Комплекты HA-004',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-ha-004',
                'published' => 1,
                '_lft' => 166,
                '_rgt' => 167,
                'parent_id' => 155,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            82 =>
            array (
                'id' => 161,
                'name' => 'Комплекты HA-010',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-ha-010',
                'published' => 1,
                '_lft' => 168,
                '_rgt' => 169,
                'parent_id' => 155,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            83 =>
            array (
                'id' => 162,
                'name' => 'Комплекты HA-016',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-ha-016',
                'published' => 1,
                '_lft' => 170,
                '_rgt' => 171,
                'parent_id' => 155,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            84 =>
            array (
                'id' => 163,
                'name' => 'Комплекты HA-032',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-ha-032',
                'published' => 1,
                '_lft' => 172,
                '_rgt' => 173,
                'parent_id' => 155,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            85 =>
            array (
                'id' => 164,
                'name' => 'Комплекты HE-006',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-he-006',
                'published' => 1,
                '_lft' => 176,
                '_rgt' => 177,
                'parent_id' => 156,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            86 =>
            array (
                'id' => 165,
                'name' => 'Комплекты HE-010',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-he-010',
                'published' => 1,
                '_lft' => 178,
                '_rgt' => 179,
                'parent_id' => 156,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            87 =>
            array (
                'id' => 166,
                'name' => 'Комплекты HE-016',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-he-016',
                'published' => 1,
                '_lft' => 180,
                '_rgt' => 181,
                'parent_id' => 156,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            88 =>
            array (
                'id' => 167,
                'name' => 'Комплекты HE-024',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-he-024',
                'published' => 1,
                '_lft' => 182,
                '_rgt' => 183,
                'parent_id' => 156,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            89 =>
            array (
                'id' => 168,
                'name' => 'Комплекты HE-032',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-he-032',
                'published' => 1,
                '_lft' => 184,
                '_rgt' => 185,
                'parent_id' => 156,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            90 =>
            array (
                'id' => 169,
                'name' => 'Комплекты HE-048',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-he-048',
                'published' => 1,
                '_lft' => 186,
                '_rgt' => 187,
                'parent_id' => 156,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            91 =>
            array (
                'id' => 170,
                'name' => 'Комплекты HSBS-004',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hsbs-004',
                'published' => 1,
                '_lft' => 190,
                '_rgt' => 191,
                'parent_id' => 157,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            92 =>
            array (
                'id' => 171,
                'name' => 'Комплекты HSB-004',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hsb-004',
                'published' => 1,
                '_lft' => 192,
                '_rgt' => 193,
                'parent_id' => 157,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            93 =>
            array (
                'id' => 172,
                'name' => 'Комплекты HSB-006',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hsb-006',
                'published' => 1,
                '_lft' => 194,
                '_rgt' => 195,
                'parent_id' => 157,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            94 =>
            array (
                'id' => 173,
                'name' => 'Комплекты HSB-012',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hsb-012',
                'published' => 1,
                '_lft' => 196,
                '_rgt' => 197,
                'parent_id' => 157,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            95 =>
            array (
                'id' => 174,
                'name' => 'Комплекты HK-004/0',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hk-0040',
                'published' => 1,
                '_lft' => 200,
                '_rgt' => 201,
                'parent_id' => 158,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            96 =>
            array (
                'id' => 175,
                'name' => 'Комплекты HK-004/2',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hk-0042',
                'published' => 1,
                '_lft' => 202,
                '_rgt' => 203,
                'parent_id' => 158,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            97 =>
            array (
                'id' => 176,
                'name' => 'Комплекты HWK-006/6',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hwk-0066',
                'published' => 1,
                '_lft' => 204,
                '_rgt' => 205,
                'parent_id' => 158,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            98 =>
            array (
                'id' => 177,
                'name' => 'Комплекты HK-006/6',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hk-0066',
                'published' => 1,
                '_lft' => 206,
                '_rgt' => 207,
                'parent_id' => 158,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            99 =>
            array (
                'id' => 178,
                'name' => 'Комплекты HK-008/0',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hk-0080',
                'published' => 1,
                '_lft' => 208,
                '_rgt' => 209,
                'parent_id' => 158,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            100 =>
            array (
                'id' => 179,
                'name' => 'Комплекты HK-004/8',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'komplekty-hk-0048',
                'published' => 1,
                '_lft' => 210,
                '_rgt' => 211,
                'parent_id' => 158,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            101 =>
            array (
                'id' => 180,
                'name' => 'Пластиковые контргайки',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'plastikovye-kontrgaiki',
                'published' => 1,
                '_lft' => 105,
                '_rgt' => 106,
                'parent_id' => 31,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            102 =>
            array (
                'id' => 181,
                'name' => 'Система кодирования',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'sistema-kodirovaniia',
                'published' => 1,
                '_lft' => 65,
                '_rgt' => 66,
                'parent_id' => 30,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            103 =>
            array (
                'id' => 182,
                'name' => 'Крепежные винты',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'krepeznye-vinty',
                'published' => 1,
                '_lft' => 67,
                '_rgt' => 68,
                'parent_id' => 30,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            104 =>
            array (
                'id' => 183,
                'name' => 'Монтажные и стыковочные рамки',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'montaznye-i-stykovocnye-ramki',
                'published' => 1,
                '_lft' => 69,
                '_rgt' => 70,
                'parent_id' => 30,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            105 =>
            array (
                'id' => 184,
                'name' => 'Инструмент для обжима',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'instrument-dlia-obzima',
                'published' => 1,
                '_lft' => 71,
                '_rgt' => 72,
                'parent_id' => 30,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            106 =>
            array (
                'id' => 185,
                'name' => 'Инструмент для установки и извлечения контактов',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'instrument-dlia-ustanovki-i-izvleceniia-kontaktov',
                'published' => 1,
                '_lft' => 73,
                '_rgt' => 74,
                'parent_id' => 30,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
            107 =>
            array (
                'id' => 186,
                'name' => 'Полукомплекты RJ45',
                'root_id' => NULL,
                'description' => '',
                'custom_title' => '',
                'order_column' => 0,
                'slug' => 'polukomplekty-rj45',
                'published' => 1,
                '_lft' => 120,
                '_rgt' => 121,
                'parent_id' => 91,
                'created_at' => '2024-09-23 18:25:28',
                'updated_at' => '2024-09-23 18:25:33',
            ),
        ));


    }
}
