<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 26,
                'root_id' => 0,
                'name' => 'Промышленные прямоугольные разъемы',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 27,
                'root_id' => 26,
                'name' => 'Контактные вставки',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 28,
                'root_id' => 26,
                'name' => 'Корпусы',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 29,
                'root_id' => 26,
                'name' => 'Обжимные контакты',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 30,
                'root_id' => 26,
                'name' => 'Аксессуары',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 31,
                'root_id' => 26,
                'name' => 'Сальники',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 33,
                'root_id' => 27,
                'name' => 'Серия HA',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 34,
                'root_id' => 27,
                'name' => 'Серия HE',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 35,
                'root_id' => 27,
                'name' => 'Серия HEE',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 36,
                'root_id' => 27,
                'name' => 'Серия HD',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 37,
                'root_id' => 27,
                'name' => 'Серия HDD',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 38,
                'root_id' => 27,
                'name' => 'Серия HSB',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 39,
                'root_id' => 27,
                'name' => 'Серия HK',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 40,
                'root_id' => 27,
                'name' => 'Серия HEAV',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 41,
                'root_id' => 27,
                'name' => 'Серия HM',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 42,
                'root_id' => 27,
                'name' => 'Серия HQ',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 43,
                'root_id' => 28,
                'name' => 'Типоразмер 3A - пластик',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 44,
                'root_id' => 28,
                'name' => 'Типоразмер 3A - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 45,
                'root_id' => 28,
                'name' => 'Типоразмер 10A - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 46,
                'root_id' => 28,
                'name' => 'Типоразмер 16A - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 47,
                'root_id' => 28,
                'name' => 'Типоразмер 32A - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 48,
                'root_id' => 28,
                'name' => 'Типоразмер 6B - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 49,
                'root_id' => 28,
                'name' => 'Типоразмер 10B - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 50,
                'root_id' => 28,
                'name' => 'Типоразмер 16B - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 51,
                'root_id' => 28,
                'name' => 'Типоразмер 24B - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 52,
                'root_id' => 28,
                'name' => 'Типоразмер 32B - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 53,
                'root_id' => 28,
                'name' => 'Типоразмер 48B - металл',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 54,
                'root_id' => 29,
                'name' => 'Обжимные контакты - 5 Ампер',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 55,
                'root_id' => 29,
                'name' => 'Обжимные контакты - 10 Ампер',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 56,
                'root_id' => 29,
                'name' => 'Обжимные контакты - 16 Ампер',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 57,
                'root_id' => 29,
                'name' => 'Обжимные контакты - 40 Ампер',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 58,
                'root_id' => 29,
                'name' => 'Обжимные контакты - 70 Ампер',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 59,
                'root_id' => 29,
                'name' => 'Обжимные контакты - 100 Ампер',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 60,
                'root_id' => 29,
                'name' => 'Обжимные контакты - 200 Ампер',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 61,
                'root_id' => 31,
                'name' => 'Пластиковые сальники',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 62,
                'root_id' => 31,
                'name' => 'Металлические сальники',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 64,
                'root_id' => 31,
                'name' => 'Металлические контргайки',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 65,
                'root_id' => 31,
                'name' => 'Пластиковые переходники',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 66,
                'root_id' => 31,
                'name' => 'Металлические переходники',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 67,
                'root_id' => 31,
                'name' => 'Футорки пластиковые',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 68,
                'root_id' => 31,
                'name' => 'Футорки металлические',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 69,
                'root_id' => 31,
                'name' => 'Пластиковые заглушки круглые',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 70,
                'root_id' => 31,
                'name' => 'Металлические заглушки шестигранные',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 71,
                'root_id' => 31,
            'name' => 'Пластиковые муфты для металлорукавов (быстрого соединения)',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 72,
                'root_id' => 31,
                'name' => 'Муфты для металлорукавов металлические прямые',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 73,
                'root_id' => 31,
                'name' => 'Металлические сальники для многожильного кабеля',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 74,
                'root_id' => 31,
                'name' => 'Металлические сальники с заземлением EMC',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 75,
                'root_id' => 31,
            'name' => 'Сальники с внешней разгрузкой от натяжения (с двойной фиксацией)',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 79,
                'root_id' => 26,
            'name' => 'Полукомплекты (кожух + вставка)',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 89,
                'root_id' => 26,
                'name' => 'Комплекты промышленных разъемов',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 90,
                'root_id' => 26,
                'name' => 'Комплекты контактных вставок',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 91,
                'root_id' => 79,
                'name' => 'Полукомплекты серии HA',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 92,
                'root_id' => 91,
                'name' => 'Полукомплекты на основе контактных вставок HA-003',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 93,
                'root_id' => 91,
                'name' => 'Полукомплекты на основе контактных вставок HA-004',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 94,
                'root_id' => 91,
                'name' => 'Полукомплекты на основе контактных вставок HA-010',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 95,
                'root_id' => 91,
                'name' => 'Полукомплекты на основе контактных вставок HA-016',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 96,
                'root_id' => 91,
                'name' => 'Полукомплекты на основе контактных вставок HA-032',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 97,
                'root_id' => 79,
                'name' => 'Полукомплекты серии HE',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 98,
                'root_id' => 97,
                'name' => 'Полукомплекты на основе контактных вставок HE-006',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 99,
                'root_id' => 97,
                'name' => 'Полукомплекты на основе контактных вставок HE-010',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 100,
                'root_id' => 97,
                'name' => 'Полукомплекты на основе контактных вставок HE-016',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 101,
                'root_id' => 97,
                'name' => 'Полукомплекты на основе контактных вставок HE-024',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 102,
                'root_id' => 97,
                'name' => 'Полукомплекты на основе контактных вставок HE-032',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 103,
                'root_id' => 97,
                'name' => 'Полукомплекты на основе контактных вставок HE-048',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 130,
                'root_id' => 79,
                'name' => 'Полукомплекты серии HSB',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 131,
                'root_id' => 130,
                'name' => 'Полукомплекты на основе контактных вставок HSBS-004',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 132,
                'root_id' => 130,
                'name' => 'Полукомплекты на основе контактных вставок HSB-004',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 133,
                'root_id' => 130,
                'name' => 'Полукомплекты на основе контактных вставок HSB-006',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 134,
                'root_id' => 130,
                'name' => 'Полукомплекты на основе контактных вставок HSB-012',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 135,
                'root_id' => 79,
                'name' => 'Полукомплекты серии HK',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 138,
                'root_id' => 135,
                'name' => 'Полукомплекты на основе контактных вставок HK-004/0',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 139,
                'root_id' => 135,
                'name' => 'Полукомплекты на основе контактных вставок HK-004/2',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 140,
                'root_id' => 135,
                'name' => 'Полукомплекты на основе контактных вставок HWK-006/6',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 144,
                'root_id' => 135,
                'name' => 'Полукомплекты на основе контактных вставок HK-006/6',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 145,
                'root_id' => 135,
                'name' => 'Полукомплекты на основе контактных вставок HK-008/0',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 146,
                'root_id' => 135,
                'name' => 'Полукомплекты на основе контактных вставок HK-004/8',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 155,
                'root_id' => 89,
                'name' => 'Комплекты серии HA',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 156,
                'root_id' => 89,
                'name' => 'Комплекты серии HE',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 157,
                'root_id' => 89,
                'name' => 'Комплекты серии HSB',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 158,
                'root_id' => 89,
                'name' => 'Комплекты серии HK',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 159,
                'root_id' => 155,
                'name' => 'Комплекты HA-003',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 160,
                'root_id' => 155,
                'name' => 'Комплекты HA-004',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 161,
                'root_id' => 155,
                'name' => 'Комплекты HA-010',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 162,
                'root_id' => 155,
                'name' => 'Комплекты HA-016',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 163,
                'root_id' => 155,
                'name' => 'Комплекты HA-032',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 164,
                'root_id' => 156,
                'name' => 'Комплекты HE-006',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 165,
                'root_id' => 156,
                'name' => 'Комплекты HE-010',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 166,
                'root_id' => 156,
                'name' => 'Комплекты HE-016',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 167,
                'root_id' => 156,
                'name' => 'Комплекты HE-024',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 168,
                'root_id' => 156,
                'name' => 'Комплекты HE-032',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 169,
                'root_id' => 156,
                'name' => 'Комплекты HE-048',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 170,
                'root_id' => 157,
                'name' => 'Комплекты HSBS-004',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 171,
                'root_id' => 157,
                'name' => 'Комплекты HSB-004',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 172,
                'root_id' => 157,
                'name' => 'Комплекты HSB-006',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 173,
                'root_id' => 157,
                'name' => 'Комплекты HSB-012',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 174,
                'root_id' => 158,
                'name' => 'Комплекты HK-004/0',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 175,
                'root_id' => 158,
                'name' => 'Комплекты HK-004/2',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 176,
                'root_id' => 158,
                'name' => 'Комплекты HWK-006/6',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 177,
                'root_id' => 158,
                'name' => 'Комплекты HK-006/6',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 178,
                'root_id' => 158,
                'name' => 'Комплекты HK-008/0',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 179,
                'root_id' => 158,
                'name' => 'Комплекты HK-004/8',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 180,
                'root_id' => 31,
                'name' => 'Пластиковые контргайки',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 181,
                'root_id' => 30,
                'name' => 'Система кодирования',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 182,
                'root_id' => 30,
                'name' => 'Крепежные винты',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 183,
                'root_id' => 30,
                'name' => 'Монтажные и стыковочные рамки',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 184,
                'root_id' => 30,
                'name' => 'Инструмент для обжима',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 185,
                'root_id' => 30,
                'name' => 'Инструмент для установки и извлечения контактов',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 186,
                'root_id' => 91,
                'name' => 'Полукомплекты RJ45',
                'description' => '',
                'image' => '',
                'published' => 0,
                'sorting' => 0,
                'slug' => '',
                'custom_title' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}